In [2]:
from pathlib import Path
import pandas as pd

In [4]:
PROJECT_ROOT = Path.cwd().parent
DATASET_PATH = PROJECT_ROOT / "data" / "bangla_news.csv"

print("Dataset exists:", DATASET_PATH.exists())

Dataset exists: True

In [5]:
df = pd.read_csv(DATASET_PATH)

print("Dataset loaded successfully")
print("Rows and Columns:", df.shape)

Dataset loaded successfully
Rows and Columns: (11904, 6)

In [6]:
print("Column names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Column names:
['title', 'published_date', 'reporter', 'category', 'url', 'content']

First 5 rows:

,title,published_date,reporter,category,url,content
0,"সিন নদীতে ব্যাপক দূষণ, স্থগিত করা হলো ট্রায়াথ...","30th July, 2024 5:59 pm",আরআইএম,sports,https://jamuna.tv/news/552127,ছবি: সংগৃহীত সিন নদীতে অলিম্পিকের উদ্বোধনী অনু...
1,এসিসির নতুন সভাপতি হচ্ছেন মহসিন নাকভি!,"30th July, 2024 5:25 pm",NaN,sports,https://jamuna.tv/news/552123,২০২৫ সালের জানুয়ারিতে এশিয়ান ক্রিকেট কাউন্স...
2,২০৩০ ও ২০৩৪ বিশ্বকাপের হোস্ট জানা যাবে দুইদিন পর!,"30th July, 2024 1:22 pm",আরআইএম,sports,https://jamuna.tv/news/552066,ফিফা বিশ্বকাপ ২০৩০ ও ৩৪ সালের স্বাগতিক হবার ল...
3,প্যারিস অলিম্পিক: কোয়ার্টার ফাইনালে ওঠার লক্ষ্...,"30th July, 2024 11:54 am",এনকে,sports,https://jamuna.tv/news/552046,প্যারিস অলিম্পিকে কোয়ার্টার ফাইনাল রেসে টিকে ...
4,আজ টিভিতে যা দেখবেন (৩০ জুলাই ২০২৪),"30th July, 2024 7:01 am",এনকে,sports,https://jamuna.tv/news/552016,আজ ভারত–শ্রীলঙ্কার তৃতীয় টি–টোয়েন্টি অলিম্পিকে...

In [7]:
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
title               0
published_date      0
reporter          990
category            0
url                 0
content             0
dtype: int64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

print("Duplicate article contents:", df["content"].duplicated().sum())

print("Duplicate URLs:", df["url"].duplicated().sum())

Duplicate rows: 0
Duplicate article contents: 59
Duplicate URLs: 55

In [9]:
df["content_length"] = df["content"].str.len()

print(df["content_length"].describe())

count    11904.000000
mean       506.579889
std        179.443955
min          2.000000
25%        392.000000
50%        483.000000
75%        594.000000
max       3455.000000
Name: content_length, dtype: float64

In [10]:
shortest = df.nsmallest(10, "content_length")

display(
    shortest[["title", "content_length", "content"]]
)

,title,content_length,content
4975,যুক্তরাষ্ট্রে একসাথে ৪৩টি গাড়ির সংঘর্ষ!,2,
11427,গুলশানে ‘কাচ্চি ভাই’কে লাখ টাকা জরিমানা,2,
6041,লাপাতা লেডিস: মিষ্টি প্রেমের মোড়কে নারীর বঞ্চন...,11,আল মাহফুজ
6103,"আবার দেখা হবে, খালিদ?",11,আল মাহফুজ
6113,তানজারিন: যে কমলা যুদ্ধ-বিরোধিতার কথা বলে,11,আল মাহফুজ
5820,ছবি: ইসরায়েলি হামলায় ঘরবাড়ি ছাড়ছেন ফিলিস্তি...,21,ছবি: আল জাজিরা। /এআই
1392,আজ টিভিতে দেখা যাবে যেসব খেলা (৬ এপ্রিল),27,আইপিএল রাজস্থান-বেঙ্গালুরু
2679,তাইজুল! দ্য আনসাং হিরো অব বাংলাদেশ,36,তাইজুল ইসলাম। ছবি: ফেসবুক পেজ। /এআই
603,আজ টিভিতে দেখা যাবে যেসব খেলা (১২ জুন),38,টি–টোয়েন্টি বিশ্বকাপ শ্রীলঙ্কা–নেপাল
1275,আজ টিভিতে দেখা যাবে যেসব খেলা (২১ এপ্রিল),40,৩য় টি–টোয়েন্টি পাকিস্তান–নিউজিল্যান্ড

In [11]:
print("Number of categories:", df["category"].nunique())

print("\nArticles per category:")
print(df["category"].value_counts())

Number of categories: 4

Articles per category:
category
sports           2976
international    2976
entertainment    2976
national         2976
Name: count, dtype: int64

In [12]:
duplicate_urls = df[df["url"].duplicated(keep=False)]

display(
    duplicate_urls[
        ["title", "url", "content_length"]
    ].sort_values("url").head(20)
)

,title,url,content_length
2801,বিশ্বকাপ ফাইনালে তারকার হাট,https://jamuna.tv/news/496707,485
6406,বিশ্বকাপ ফাইনালে তারকার হাট,https://jamuna.tv/news/496707,485
2555,শাহরুখ-প্রীতির পর ক্রিকেটে দল কিনলেন অক্ষয়,https://jamuna.tv/news/502700,428
6340,শাহরুখ-প্রীতির পর ক্রিকেটে দল কিনলেন অক্ষয়,https://jamuna.tv/news/502700,428
11874,সকল গীতিকারই ‘কবি’ নয়: লতিফুল ইসলাম শিবলী,https://jamuna.tv/news/517105,733
6209,সকল গীতিকারই ‘কবি’ নয়: লতিফুল ইসলাম শিবলী,https://jamuna.tv/news/517105,733
4772,সড়ক দুর্ঘটনায় প্রাণ গেল ম্যারাথনে বিশ্ব রেকর...,https://jamuna.tv/news/517145,586
1966,সড়ক দুর্ঘটনায় প্রাণ গেল ম্যারাথনে বিশ্ব রেকর...,https://jamuna.tv/news/517145,586
4688,নিউইয়র্কে ইলিয়াস হোসেন গ্রেফতার,https://jamuna.tv/news/518532,328
11768,নিউইয়র্কে ইলিয়াস হোসেন গ্রেফতার,https://jamuna.tv/news/518532,328
11737,বাংলাদেশের মানুষ ‘মায়ের মতো ভালো’: অনিন্দ্য চট...,https://jamuna.tv/news/518825,772
6188,বাংলাদেশের মানুষ ‘মায়ের মতো ভালো’: অনিন্দ্য চট...,https://jamuna.tv/news/518825,772
1866,ভিরাট-আনুশকার ঘরে নতুন অতিথি,https://jamuna.tv/news/518944,310
6186,ভিরাট-আনুশকার ঘরে নতুন অতিথি,https://jamuna.tv/news/518944,310
6183,আমাদের একুশের গান,https://jamuna.tv/news/519065,361
11716,আমাদের একুশের গান,https://jamuna.tv/news/519065,361
11704,পরীমণির বিরুদ্ধে মাদক মামলার বিচার চলবে: হাইকোর্ট,https://jamuna.tv/news/519322,637
6179,পরীমণির বিরুদ্ধে মাদক মামলার বিচার চলবে: হাইকোর্ট,https://jamuna.tv/news/519322,637
11643,প্রকাশিত হলো রুদ্র আরিফের ‘সিনেঅলা ৪’,https://jamuna.tv/news/520233,547
6167,প্রকাশিত হলো রুদ্র আরিফের ‘সিনেঅলা ৪’,https://jamuna.tv/news/520233,547

In [13]:
short_articles = df[df["content_length"] < 100]

print("Articles shorter than 100 characters:", len(short_articles))

display(
    short_articles[
        ["title", "content_length", "content"]
    ].head(20)
)

Articles shorter than 100 characters: 18

,title,content_length,content
603,আজ টিভিতে দেখা যাবে যেসব খেলা (১২ জুন),38,টি–টোয়েন্টি বিশ্বকাপ শ্রীলঙ্কা–নেপাল
1275,আজ টিভিতে দেখা যাবে যেসব খেলা (২১ এপ্রিল),40,৩য় টি–টোয়েন্টি পাকিস্তান–নিউজিল্যান্ড
1295,আজ টিভিতে দেখা যাবে যেসব খেলা (১৭ এপ্রিল),57,উয়েফা চ্যাম্পিয়নস লিগ ম্যানচেস্টার সিটি–রিয...
1392,আজ টিভিতে দেখা যাবে যেসব খেলা (৬ এপ্রিল),27,আইপিএল রাজস্থান-বেঙ্গালুরু
2679,তাইজুল! দ্য আনসাং হিরো অব বাংলাদেশ,36,তাইজুল ইসলাম। ছবি: ফেসবুক পেজ। /এআই
3093,সপ্তাহের আলোচিত কিছু ছবি ও গল্প,96,চলতি সপ্তাহে বিশ্বজুড়ে তোলা আকর্ষণীয় কিছু ফ...
4975,যুক্তরাষ্ট্রে একসাথে ৪৩টি গাড়ির সংঘর্ষ!,2,
5790,"ফিলিপাইনের ক্যাথলিক সমাবেশে বিস্ফোরণ, নিহত ৪",91,ফিলিপাইনের মিন্দানাও স্টেট ইউনিভার্সিটির জিমনে...
5820,ছবি: ইসরায়েলি হামলায় ঘরবাড়ি ছাড়ছেন ফিলিস্তি...,21,ছবি: আল জাজিরা। /এআই
5864,ছবিতে এক নজরে বন্যা ও তুষারঝড়ে বিপর্যস্ত ইউক্র...,87,রাশিয়ার ব্ল্যাক সি বন্দরে বড় বড় ঢেউ শহরের সম...
6026,"পিয়ালের দেহখান, নিও না শ্মশান, এমনিতেও পুড়ে গে...",67,'অড সিগনেচার' ব্যান্ডের আহাসান তানভীর পিয়াল। ছ...
6041,লাপাতা লেডিস: মিষ্টি প্রেমের মোড়কে নারীর বঞ্চন...,11,আল মাহফুজ
6103,"আবার দেখা হবে, খালিদ?",11,আল মাহফুজ
6113,তানজারিন: যে কমলা যুদ্ধ-বিরোধিতার কথা বলে,11,আল মাহফুজ
6397,করণের শোয়ে বিতর্ক: দীপিকার হয়ে গর্জে উঠলেন টুই...,67,টুইঙ্কেল খান্না (বামে) ও দীপিকা পাড়ুকোন। ছবি:...
6423,ছবিতে এক নজরে ৩০ বছরে পা দেয়া ‘বাজিগর’,41,'বাজিগর' সিনেমার পোস্টার। ছবি: সংগৃহীত।
11427,গুলশানে ‘কাচ্চি ভাই’কে লাখ টাকা জরিমানা,2,
11727,অমর একুশে ফেব্রুয়ারি আজ,53,ছবি: সংগৃহীত ফেব্রুয়ারির একুশ তারিখ দুপুর বেল...

In [14]:
duplicate_content = df[
    df["content"].duplicated(keep=False)
].sort_values("content")

display(
    duplicate_content[
        ["title", "url", "content"]
    ].head(10)
)

,title,url,content
4975,যুক্তরাষ্ট্রে একসাথে ৪৩টি গাড়ির সংঘর্ষ!,https://jamuna.tv/news/513880,
11427,গুলশানে ‘কাচ্চি ভাই’কে লাখ টাকা জরিমানা,https://jamuna.tv/news/522832,
11737,বাংলাদেশের মানুষ ‘মায়ের মতো ভালো’: অনিন্দ্য চট...,https://jamuna.tv/news/518825,অনিন্দ্য চট্টোপাধ্যায়ের পরিচয়ের অন্ত নেই। জনপ...
6188,বাংলাদেশের মানুষ ‘মায়ের মতো ভালো’: অনিন্দ্য চট...,https://jamuna.tv/news/518825,অনিন্দ্য চট্টোপাধ্যায়ের পরিচয়ের অন্ত নেই। জনপ...
6167,প্রকাশিত হলো রুদ্র আরিফের ‘সিনেঅলা ৪’,https://jamuna.tv/news/520233,অমর একুশে বইমেলায় প্রকাশিত হয়েছে চলচ্চিত্র ...
11643,প্রকাশিত হলো রুদ্র আরিফের ‘সিনেঅলা ৪’,https://jamuna.tv/news/520233,অমর একুশে বইমেলায় প্রকাশিত হয়েছে চলচ্চিত্র ...
6113,তানজারিন: যে কমলা যুদ্ধ-বিরোধিতার কথা বলে,https://jamuna.tv/news/525153,আল মাহফুজ
6103,"আবার দেখা হবে, খালিদ?",https://jamuna.tv/news/526166,আল মাহফুজ
6041,লাপাতা লেডিস: মিষ্টি প্রেমের মোড়কে নারীর বঞ্চন...,https://jamuna.tv/news/534443,আল মাহফুজ
4264,"মালয়েশিয়ায় মর্গে পড়ে আছে বাংলাদেশির মরদেহ,...",https://jamuna.tv/news/527027,"আহমাদুল কবির, মালয়েশিয়া: মালয়েশিয়ার পেরাক..."